name: ossproj_comfyride
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.28.0
  firebase_database: ^10.0.15
  cloud_firestore: ^4.16.0
  http: ^1.2.1
  image_network: ^2.5.6
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.4
  url_launcher: ^6.2.6
  giffy_dialog: ^2.1.0
  csv: ^6.0.0
  cached_network_image: ^3.2.0
  provider: ^6.0.3
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/